### ISSUE TITLE
emscripten_get_element_css_size

### ISSUE THREAD

**Issue by nickdesaulniers** [Daft-Freak/SDL-emscripten#22]
`emscripten_get_element_css_size` is not yet available to developers using the emscripten sdk.  Is it possible to have separate master and incoming branches that stay in sync with emscripten?

**Comment by Daft-Freak** [comment]
Fixed by https://github.com/kripken/emscripten/commit/6db79ca041d1014b96ce6af055fc147a5a7ebdce back in Oct 2014
