### ISSUE TITLE
Pending items before merging upstream.

### ISSUE THREAD

**Issue by urkle** [Daft-Freak/SDL-emscripten#26]
Now that we have successfully used this fork in the Humble Mozilla bundle in 6 games!  My next item on the agenda is to work on getting this merged upstream into the official SDL2 repository.

I'd like to create a list of issues linked to here of things that must be fixed before that happens.  Ryan Gordon is anxious and even would like to get it into the 2.0.4 release.

**Comment by Daft-Freak** [comment]
I've synced ports with upstream. It's currently on a branch: https://github.com/emscripten-ports/SDL2/tree/upstream_sync

**Comment by kripken** [comment]
Thanks, I took a quick look at the emscripten-related changes and saw nothing odd. Also the test suite passes on the branch. So I think we can merge it in, unless there are other things we want to do before?

**Comment by Daft-Freak** [comment]
emscripten-ports should be up to date now.

**Comment by Daft-Freak** [comment]
These should be sent upstream: https://github.com/Daft-Freak/SDL-emscripten/compare/cbfa42a...ca20edf

**Comment by urkle** [comment]
I'll take a look at through over the weekend and get them up there.

**Comment by kripken** [comment]
@Daft-Freak , I see `browser.test_sdl2_mouse` and `browser.test_sdl2_mouse_offsets` are now broken. They passed when I tested the merge, so I think one of your later mouse-related commits might be the cause?

**Comment by kripken** [comment]
Hmm, re-running those tests, they pass. Perhaps an intermittent problem on my local machine?

**Comment by Daft-Freak** [comment]
Everything is upstreamed.
